### ISSUE TITLE
"Single-level" FreeSpec-tests broken in version 3

### ISSUE THREAD

**Issue by LimmaPaulus** [kotlintest/kotlintest#298]
After upgrading from 2.0.7 to 3.0.4, following code produces syntax error:

```
class Tests : FreeSpec(){

    init {
        "test should pass"{
        }
    }
}
```

"Expression 'test should pass' of type 'String' cannot be invoked as a function. The function invoke() is not found"

This works well:

```
class Tests : FreeSpec() {
    init {
        "test" - {
            "should pass"{
            }
        }
    }
}
```

I know that StringSpec provides this functionality, but I would like to mix these two styles in the same class.

**Comment by sksamuel** [comment]
I don't see why not.

**Comment by LimmaPaulus** [comment]
I dont't know more about the reasons of problem, but I'm getting compilation error with exactly same code as above

"Expression 'test should pass' of type 'String' cannot be invoked as a function. The function invoke() is not found"

I'm using Android Studio 3.1.1

**Comment by sksamuel** [comment]
I mean I don't see why we can't add suppirt. In other words I'll make it work in 3.1

**Comment by LimmaPaulus** [comment]
:thumbsup:

**Comment by sksamuel** [comment]
We can leave this open as a reminder.

**Comment by sksamuel** [comment]
Fixed in 3.1.0-RC2 and 3.0.6
