### ISSUE TITLE
Can't run tests in Android Studio OR Gradle with kotlintest-runner-junit4 > 3.1.5, can't run tests with Gradle with kotlintest-runner-junit4:3.1.5

### ISSUE THREAD

**Issue by jeffreyfjohnson** [kotlintest/kotlintest#496]
I'm having some trouble setting up kotlintest in an Android project. We currently have two types of tests in our project, both using the JUnit4 test runner. This is maybe related to issue #385 

We have JUnit4 tests that look like this:
```
@RunWith(JUnit4::class)
class PokoTest {
    @Test
    fun test() {
        assertThat(1).isEqualTo(1)
    }
}
```

We have Robolectric tests (for when we need to access Android classes to test) that look like this:
```
@RunWith(RobolectricTestRunner::class)
class RobolectricStringFormatterTest {
    // Robolectric allows us to access an Android Context to load system resources, among other things
    private val context = RuntimeEnvironment.application 
    private val subject = StringFormatter(context)

    @Test
    fun anotherTest() {
        assertThat(subject.format("abc")).isEqualTo("a-b-c")
    }
}
```

I would like to start migrating to using the different style Specs in place of JUnit4 tests.

However I can't get the tests to run in both Android Studio (v3.2.1) which we need for development, and through the command line/gradle which we need for our CI.

Here is our app-level `build.gradle` (tried to pare it down a bit)

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

repositories {
    jcenter()
    mavenCentral()
    google()
    maven { url 'https://repository.apache.org/content/repositories/snapshots/' }
    maven { url 'https://jitpack.io' }
    maven { url 'https://maven.fabric.io/public' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}

androidExtensions {
    experimental = true
}

tasks.withType(Test) {
    testLogging {
        events "passed", "skipped", "failed"
    }
}

android {
    compileSdkVersion 28
    buildToolsVersion '27.0.3'
    defaultConfig {
        applicationId 'com.foo.bar'
        minSdkVersion 21
        targetSdkVersion 28
    }
    dataBinding {
        enabled = true
    }
    dexOptions {
        preDexLibraries true
    }
    testOptions {
        unitTests.includeAndroidResources = true
        unitTests.all {
            useJUnitPlatform()
        }
    }
    sourceSets {
        main
        release
    }
}

dependencies {
    def versionArchLifecycle = '1.1.1'
    def versionRobolectric = '3.8'
    testImplementation("android.arch.core:core-testing:$versionArchLifecycle", {
        exclude group: 'com.android.support', module: 'support-compat'
        exclude group: 'com.android.support', module: 'support-annotations'
        exclude group: 'com.android.support', module: 'support-core-utils'
    })
    testImplementation 'com.nhaarman:mockito-kotlin-kt1.1:1.5.0'
    testImplementation('com.squareup:fest-android:1.0.8') {
        exclude group: 'com.android.support', module: 'support-v4'
    }
    testImplementation 'org.mockito:mockito-core:2.18.3'
    testImplementation "org.robolectric:robolectric:$versionRobolectric"
    testImplementation "org.robolectric:shadows-httpclient:$versionRobolectric"
    testImplementation "org.robolectric:shadows-multidex:$versionRobolectric"
    testImplementation "org.robolectric:shadows-playservices:$versionRobolectric"
    testImplementation "org.robolectric:shadows-supportv4:$versionRobolectric"
    testImplementation 'com.github.javafaker:javafaker:0.13'
    testImplementation "com.android.support.test:runner:1.0.2"
    testImplementation "com.android.support.test:rules:1.0.2"
    
    testImplementation 'io.kotlintest:kotlintest-runner-junit4:3.1.5'
}

kotlin {
    experimental {
        coroutines "enable"
    }
}
```

When we use `'io.kotlintest:kotlintest-runner-junit4:3.1.5'`, all types of test (JUnit4, Robolectric, KotlinTest) run just fine in Android Studio. However, running `./gradlew testLocalDebugUnitTest --tests {a JUnit4 test, a Robolectric test, or a KotlinTest test class name}`, I get the error: `No tests found for given includes: [{whatever test class name(s) passed in to command}]`. When I try to run all tests using the command `./gradlew testLocalDebugUnitTest` I see a test report with this exception:
```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 3.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.junit.platform.commons.util.PreconditionViolationException: Cannot create Launcher without at least one TestEngine; consider adding an engine implementation JAR to the classpath
	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:285)
	at org.junit.platform.launcher.core.DefaultLauncher.<init>(DefaultLauncher.java:55)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:59)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$100(JUnitPlatformTestClassProcessor.java:77)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:73)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	... 25 more
```

When we use `'io.kotlintest:kotlintest-runner-junit4:3.1.10'`, I can't run any type of test in Android Studio, and I see this error in the console: `Exception in thread "main" java.lang.NoClassDefFoundError: org/junit/platform/launcher/TestExecutionListener` (related to #385 ?), plus I get the same error when trying to run tests through the command line.

I'm happy to close this issue if it's just an issue with my setup, but I can't seem to figure out where that issue might be

**Comment by jeffreyfjohnson** [comment]
Not sure if this is helpful, but if I remove 
```
unitTests.all {
    useJUnitPlatform()
}
```

I can run all tests through the command line/Gradle, both on `kotlintest-runner-junit4:3.1.10` and `kotlintest-runner-junit4:3.1.5`.

I still have the same issue on 3.1.10 running tests in Studio, but on 3.1.5 the tests still run fine in Studio.

So as a temporary workaround, just removing the `useJUnitPlatform` and staying on 3.1.5 seems to work for our use case

**Comment by jeffreyfjohnson** [comment]
@Kerooker I am running Android Studio v3.2.1. Not sure what version of Intellij that corresponds to.

Our gradle wrapper version is 4.7

I will try your suggestions, starting with the invalidate/restart, although I do believe I've tried that already.

Thanks for the quick reply!

**Comment by Kerooker** [comment]
It's likely that you tried it already. But every bug in android starts with "try to invalidate caches and restart"

**Comment by Kerooker** [comment]
But if you're able to (it would be awesome if you could!), can we try to pinpoint exactly the version that started this issue?

You said that with 3.1.5 everything runs fine (flawlessly? never errors?). But we have some more versions before 3.1.10, if you could try them:

- [ x ] 3.1.5
- [  ] 3.1.6
- [  ] 3.1.7
- [  ] 3.1.8
- [  ] 3.1.9
- [  ] 3.1.10 

We know for sure that it doesn't work in 3.1.10 and that it works in 3.1.5

**Comment by jeffreyfjohnson** [comment]
3.1.6 does not work in Android studio, same `NoClassDefFoundError`. I assume that means all following releases will also not work.

I will try the steps outline in the SO post later today and get back to you

**Comment by Kerooker** [comment]
Interesting. This is a point to start digging, by release 3.1.6.

Thanks! That a lot of help already :)

**Comment by Kerooker** [comment]
I think that the only commit from 3.1.5 to 3.1.6 that may change something in JUnit's execution is https://github.com/kotlintest/kotlintest/commit/5124afacf4c57fb873f732b4a9803dc5e74085ac. @sksamuel Do you believe this may be causing issues with Intellij/Android Studio, when it tries to execute a JUnit 4 test?

**Comment by sksamuel** [comment]
Yes possibly. That annotation exists purely so that the little "run" icon appears in intellij, because it looks for the presence of these annotations in a file to determine if a class is a test class or not.

**Comment by jeffreyfjohnson** [comment]
@Kerooker Adding the `compileDebugUnitTestKotlin` step does not allow tests to run in Android Studio for versions > 3.1.5, neither does invalidating/restarting.

For now I will stay on version 3.1.5 which allows the tests to run in Studio, and remove the `useJUnitPlatform`, which allows tests to run via Gradle.

Thanks for the help

**Comment by Kerooker** [comment]
@jeffreyfjohnson And you can execute the class via the the run icon even before 3.1.6?

**Comment by Kerooker** [comment]
I couldn't reproduce this issue.
No answer from OP in a good time
No other users having this problem.

I'll be closing this. Feel free to open a new issue if you can reproduce it
